version: '3'

services:

  mw-mysql:
    container_name: mysql        # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ljro4HrJpKJGc5Pv
    #env_file: 设置环境变量文件
    #  - .env  
    volumes:
      - /data/mysql:/var/lib/mysql           # 挂载数据目录
      - ./my.cnf:/etc/my.cnf